kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: northwind
  labels:
    app: northwind
    tier: frontend
spec:
  scaleTargetRef:
    kind:       Deployment
    apiVersion: apps/v1
    name:       website
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
