apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-db
  labels:
    tier: backend
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      protocol: TCP
      name: mongodb
  selector:
    tier: backend
    {{- include "chart.selectorLabels" . | nindent 4 }}
