apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-db
  labels:
    app: {{ include "chart.name" . }}-db
    version: {{ .Chart.AppVersion | quote }}
    tier: backend
    {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "chart.name" . }}-db
      version: {{ .Chart.AppVersion | quote }}
      tier: backend
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "chart.name" . }}-db
        version: {{ .Chart.AppVersion | quote }}
        tier: backend
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.backend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.backend.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-db
          securityContext:
            {{- toYaml .Values.backend.securityContext | nindent 12 }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.version }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: 27017
              protocol: TCP
        {{- if .Values.backend.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: /data/db
        {{- end }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}

    {{- if .Values.backend.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
          {{- if .Values.backend.persistence.existingClaim }}
            claimName: {{ .Values.backend.persistence.existingClaim }}
          {{- else }}
            claimName: {{ include "chart.fullname" . }}-db
          {{- end }}
    {{- end }}

    {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}

    {{- with .Values.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}

    {{- with .Values.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
