{{- if .Values.frontend.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    app: {{ include "chart.name" . }}-website
    tier: frontend
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: {{ include "chart.name" . }}-website
    tier: frontend
    {{- include "chart.selectorLabels" . | nindent 4 }}
{{- end }}
